version: '3'

services:
  postgres-db:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
